print("Traceback (most recent call last):")
print(" File 'main.py', line 58, in <module>")
print("  tf.app.run()")
print(" File 'main.py', line 40, in main")
print("  dcgan.train(FLAGS)")
print(" File '/home/amine/workspace/DCGAN-tensorflow/model.py', line 150, in train")
print("  feed_dict={ self.images: batch_images, self.z: batch_z })")
print("tensorflow.python.framework.errors.InvalidArgumentError: tags and values not the same shape: [] != [64,1] (tag 'd_loss_real')")
print("   [[Node: ScalarSummary = ScalarSummary[T=DT_FLOAT, _device='/job:localhost/replica:0/task:0/cpu:0'](ScalarSummary/tags, logistic_loss)]]")
