print("Traceback (most recent call last):")
print(" File '/usr/local/lib/python3.6/dist-packages/absl/flags/_flag.py', line 181, in _parse")
print("  return self.parser.parse(argument)")
print(" File '/usr/local/lib/python3.6/dist-packages/absl/flags/_argument_parser.py', line 171, in parse")
print("  val = self.convert(argument)")
print(" File '/usr/local/lib/python3.6/dist-packages/absl/flags/_argument_parser.py', line 287, in convert")
print("  type(argument)))")
print(" File '/home/metadata/DCGAN-tensorflow108-buggy/model.py',line 14, in conv_out_size_same")
print("  return math.ceil(float(size) / float(stride))")
print("TypeError: Expect argument to be a string or int, found <class 'float'>")

